# permissions for end users to edit cpureaperpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cpu-reaper-operator
    app.kubernetes.io/managed-by: kustomize
  name: cpureaperpolicy-editor-role
rules:
- apiGroups:
  - reaper.cpu.limit.check
  resources:
  - cpureaperpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reaper.cpu.limit.check
  resources:
  - cpureaperpolicies/status
  verbs:
  - get
